development:
  dialect: postgres
  database: taxcalculator_api_development
  user: postgres
  password: postgres123
  host: 127.0.0.1
  pool: 5
  url: {{envOr "DATABASE_URL" ""}}

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres123@127.0.0.1:5432/taxcalculator_api_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres123@127.0.0.1:5432/taxcalculator_api_production?sslmode=disable"}}
