version: '3'

services:
  db:
    image: postgres:10-alpine
    container_name: taxcalculator_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: taxcalculator_api_production
      POSTGRES_PASSWORD: postgres123
    ports:
      - 5432:5432
    restart: always
    # Un-comment the following two lines if you want data to persist across containers
    volumes:
      - pg-data:/var/lib/postgresql/data
      
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile-prod
    container_name: taxcalculator-api
    restart: always
    environment: 
      - SESSION_SECRET=I8RBTQSKZSIMZ8UTNOKSLPFA
      - DATABASE_URL=postgres://postgres:postgres123@db:5432/taxcalculator_api_production?sslmode=disable
    ports:
      - 3000:3000
    tty:
      true

volumes:
  pg-data: