version: '2.1'
services:
  db:
    image: postgres:9.6.11
    volumes:
      - ./database_data:/var/lib/postgresql/data
    # networks:
      # - local
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=taxcalculator_api_development
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    command: buffalo pop migrate && buffalo dev
    ports:
      - 3000:3000
    volumes:
      - .:/bin
    # networks:
      # - local
    restart: always
    environment:
      - GO_ENV=development
      - DATABASE_URL=postgres://postgres:postgres123@db/taxcalculator_api_development?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    working_dir: /bin

# networks:
  # local:

volumes:
    database_data:
      driver: local