# This is a multi-stage Dockerfile and requires >= Docker 17.05
# https://docs.docker.com/engine/userguide/eng-image/multistage-build/
FROM riesal/gobuffalo:latest as builder

RUN mkdir -p $GOPATH/src/github.com/halimindra/taxcalculator-api
WORKDIR $GOPATH/src/github.com/halimindra/taxcalculator-api

ADD . .
RUN go get -u github.com/golang/dep/cmd/dep
RUN dep ensure

ENV ADDR=0.0.0.0

EXPOSE 3000

# Uncomment to run the migrations before running the binary:
# RUN /bin/app migrate
# CMD /bin/app migrate; /bin/app
# CMD exec /bin/app
